### PR TITLE
fix(hover): at rules support & refactor

### LINKED ISSUE #17: `crates/csslsrs/src/features/hover.rs`: at rules hover doesn't work
### Describe the Bug

```rs
CssSyntaxKind::CSS_IDENTIFIER => {
                // Handle identifiers like properties or at-rules
                if let Some(hover_content) =
                    get_css_hover_content(ancestor.kind(), token.text().trim(), css_data)
                {
                    return Some(Hover {
                        contents: HoverContents::Markup(MarkupContent {
                            kind: MarkupKind::Markdown,
                            value: hover_content,
                        }),
                        range: range(line_index, ancestor.text_trimmed_range(), encoding).ok(),
                    });
                }
            }
[...]
        // Handle at-rules like @media, @supports, etc.
        CssSyntaxKind::CSS_AT_RULE => {
            eprintln!("Looking for at-rule: {}", name);
            for data in css_data {
                if let Some(at_directive) = data
                    .at_directives
                    .as_ref()
                    .iter()
                    .flat_map(|ats| ats.iter())
                    .find(|at| at.name == name)
                {
                    return Some(format_css_at_rule_entry(at_directive));
                }
            }
            None
        }
```

This code does absolutely not match at_rules... Here is the CST for `@media screen and (min-width: 900px) {}` :
```
0: CSS_ROOT@0..39
  0: (empty)
  1: CSS_RULE_LIST@0..39
    0: CSS_AT_RULE@0..39
      0: AT@0..1 "@" [] []
      1: CSS_MEDIA_AT_RULE@1..39
        0: MEDIA_KW@1..7 "media" [] [Whitespace(" ")]
        1: CSS_MEDIA_QUERY_LIST@7..37
          0: CSS_MEDIA_AND_TYPE_QUERY@7..37
            0: CSS_MEDIA_TYPE_QUERY@7..14
              0: (empty)
              1: CSS_MEDIA_TYPE@7..14
                0: CSS_IDENTIFIER@7..14
                  0: IDENT@7..14 "screen" [] [Whitespace(" ")]
            1: AND_KW@14..18 "and" [] [Whitespace(" ")]
            2: CSS_MEDIA_FEATURE_IN_PARENS@18..37
              0: L_PAREN@18..19 "(" [] []
              1: CSS_QUERY_FEATURE_PLAIN@19..35
                0: CSS_IDENTIFIER@19..28
                  0: IDENT@19..28 "min-width" [] []
                1: COLON@28..30 ":" [] [Whitespace(" ")]
                2: CSS_REGULAR_DIMENSION@30..35
                  0: CSS_NUMBER_LITERAL@30..33 "900" [] []
                  1: IDENT@33..35 "px" [] []
              2: R_PAREN@35..37 ")" [] [Whitespace(" ")]
        2: CSS_RULE_BLOCK@37..39
          0: L_CURLY@37..38 "{" [] []
          1: CSS_RULE_LIST@38..38
          2: R_CURLY@38..39 "}" [] []
  2: EOF@39..39 "" [] []
``` 

Maybe I should take inspiration from my code on `document_symbols.rs`

### What's the expected result?

In `crates/csslsrs/tests/hover.rs`, the ignored test `test_hover_at_rule` should pass.

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by goulvenclech**
Fixes #17 and improves the logic.

## What does this change?

* `crates/csslsrs/src/features/hover.rs`: Added the support for at_rules.
* `crates/csslsrs/src/features/hover.rs`: Removed the `get_css_hover_content` function and integrated its logic directly into the `extract_hover_information` function to reduce redundancy.
* `crates/csslsrs/src/features/hover.rs`: Refactored the `extract_hover_information` function to streamline the process of finding relevant CSS nodes and generating hover content.

## How is it tested?

Added two new tests for at-rules in `crates/csslsrs/tests/hover.rs` (technically one already existed and I just unskipped it but you get it)

## How is it documented?

Matches the expected behaviour.

### CODE REVIEW

File: crates/csslsrs/src/features/hover.rs [hunk 1]
```diff
@@ -1,131 +1,110 @@
...
+use std::fmt::Write;
 
 /// Extracts hover information for the given CSS node and position.
 fn extract_hover_information(
     node: &SyntaxNode<CssLanguage>,
     position: Position,
     line_index: &LineIndex,
     encoding: PositionEncoding,
-    css_data: &Vec<&CssCustomData>,
+    css_data: &[&CssCustomData],
```
Comment (Princesseuh) [inline crates/csslsrs/src/features/hover.rs:27]: ?

Comment (goulvenclech) [reply crates/csslsrs/src/features/hover.rs:27]: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
`#[warn(clippy::ptr_arg)]` on by default

**Review by Princesseuh — APPROVED** [review]
looks great
